language: node_js
node_js:
  - "12.20.0"
  - "14.13.1"
  - "16.0.0"
cache:
  directories:
    - node_modules
before_install:
  # Update Node.js modules
  - |
    # Prune and rebuild node_modules
    if [[ -d node_modules ]]; then
      npm prune
      npm rebuild
    fi
before_script:
  - |
    # Contents of node_modules
    npm -s ls ||:
script:
  - |
    # Run test script
    npm run-script test-ci
  - |
    # Run linting
    npm run-script lint
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@2.13.3
    c8 report --reporter=text-lcov | coveralls
